// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQuLxBFv5N6WoA0x7RiWijOBGlbvAYapU',
    appId: '1:1039647790964:web:2e91ddbe453fa1de7b3e21',
    messagingSenderId: '1039647790964',
    projectId: 'chat-app-96289',
    authDomain: 'chat-app-96289.firebaseapp.com',
    storageBucket: 'chat-app-96289.appspot.com',
    measurementId: 'G-0G8E38DW1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPXdzFBkm-rjNpkc03ayQurg_5vaZUbTE',
    appId: '1:1039647790964:android:44825d581ee3cf5b7b3e21',
    messagingSenderId: '1039647790964',
    projectId: 'chat-app-96289',
    storageBucket: 'chat-app-96289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MJTYzGKV-boOT0H0XL8kPWrmqAdcvco',
    appId: '1:1039647790964:ios:dd5d119bf8586adc7b3e21',
    messagingSenderId: '1039647790964',
    projectId: 'chat-app-96289',
    storageBucket: 'chat-app-96289.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_MJTYzGKV-boOT0H0XL8kPWrmqAdcvco',
    appId: '1:1039647790964:ios:dd5d119bf8586adc7b3e21',
    messagingSenderId: '1039647790964',
    projectId: 'chat-app-96289',
    storageBucket: 'chat-app-96289.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQuLxBFv5N6WoA0x7RiWijOBGlbvAYapU',
    appId: '1:1039647790964:web:e043870e2acaeedd7b3e21',
    messagingSenderId: '1039647790964',
    projectId: 'chat-app-96289',
    authDomain: 'chat-app-96289.firebaseapp.com',
    storageBucket: 'chat-app-96289.appspot.com',
    measurementId: 'G-D247HBJTY7',
  );

}